apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zeeks.edcop.io
spec:
  group: edcop.io
  names:
    kind: Zeek
    listKind: ZeekList
    plural: zeeks
    singular: zeek
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
